<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Cache;

class Article extends Model
{
    use HasFactory;
    protected $fillable = [
        'titre',
        'chapeau',
        'article',
        'image',
        'keyword',
        'imagewidth',
        'imageheigth',
        'slug',
        'dateparution',
        'user_id',
        'rubrique_id',
        'pays_code',

    ];
    public $timestamps = false;
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Article::created(function($model){
            Cache::forget('article-list');
        });
        Article::deleted(function($model){
            Cache::forget('article-list');
        });
        Article::updated(function($model){
            Cache::forget('article-list');
        });
    }
    public function users():HasMany{
        return $this->hasMany(User::class);
    }
    public function rubriques():HasMany{
        return $this->hasMany(Rubrique::class);
    }
    public function pays():HasMany{
        return $this->hasMany(Pays::class);
    }
}
