<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Cache;

class Publicite extends Model
{
    use HasFactory;
    protected $fillable = [
        'datefin',
        'publicite',
        'typepub_id',

    ];
    public $timestamps = false;
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Publicite::created(function($model){
            Cache::forget('publicite-list');
        });
        Publicite::deleted(function($model){
            Cache::forget('publicite-list');
        });
        Publicite::updated(function($model){
            Cache::forget('publicite-list');
        });
    }
    public function typepubs():HasMany{
        return $this->hasMany(Typepub::class);
    }
}
