<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Cache;

class Role extends Model
{
    use HasFactory;
    protected $fillable = [
        'role',

    ];
    public $timestamps = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Role::created(function($model){
            Cache::forget('role-list');
        });
        Role::deleted(function($model){
            Cache::forget('role-list');
        });
        Role::updated(function($model){
            Cache::forget('role-list');
        });
    }
    public function user():BelongsTo{
        return $this->belongsTo(User::class);
    }
    
}
