<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Cache;

class Rubrique extends Model
{
    use HasFactory;

    protected $fillable = [
        'rubrique',
        'slugrubrique',
        'categorie_id',

    ];
    public $timestamps = false;
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Rubrique::created(function($model){
            Cache::forget('rubrique-list');
        });
        Rubrique::deleted(function($model){
            Cache::forget('rubrique-list');
        });
        Rubrique::updated(function($model){
            Cache::forget('rubrique-list');
        });
    }
    public function categories():HasMany{
        return $this->hasMany(Categorie::class);
    }
}
