<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class Typepub extends Model
{
    use HasFactory;
    protected $fillable = [
        'typepub',
        'slugtypepub',

    ];
    public $timestamps = false;
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Typepub::created(function($model){
            Cache::forget('typepub-list');
        });
        Typepub::deleted(function($model){
            Cache::forget('typepub-list');
        });
        Typepub::updated(function($model){
            Cache::forget('typepub-list');
        });
    }
    public function publicte(){
        return $this->belongsTo(Publicite::class);
    }
}
