<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class Video extends Model
{
    use HasFactory;
    protected $fillable = [
        'titre',
        'video',
        'typevideo',
        'typevideo',
    ];
    public $timestamps = false;
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Video::created(function($model){
            Cache::forget('video-list');
        });
        Video::deleted(function($model){
            Cache::forget('video-list');
        });
        Video::updated(function($model){
            Cache::forget('video-list');
        });
    }
}
