<?php

namespace App\Repositories;

use App\Repositories\BaseRepository;
use App\Models\Categorie;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\Cache;
class CategorieRepository extends BaseRepository
{
    public function __construct(Categorie $categorie)
    {
        $this->model=$categorie;
    }

    public function findById($id)
    {
        return parent::findById($id); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function update(array $input, $id)
    {
        $input["categorie"]=Str::title($input["categorie"]);
        $input["slugcategorie"]=Str::slug($input["categorie"]);
        return parent::update($input, $id); // TODO: Change the autogenerated stub
    }

    public function create(array $input)
    {
        $input["categorie"]=Str::title($input["categorie"]);
        $input["slugcategorie"]=Str::slug($input["categorie"]);
        $data= parent::create($input); // TODO: Change the autogenerated stub
        return parent::findById($data->id);
    }
    public function findAll(){
        if($categorie=Cache::get('categorie-list')){
            return $categorie;
        }
        $categorie=Categorie::orderBy('categorie','asc')->paginate();
        Cache::set('categorie-list',$categorie,Carbon::now()->addMinute(60));
        return $categorie;
    }

}
