<?php

namespace App\Repositories;

use App\Repositories\BaseRepository;
use App\Models\Role;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\Cache;
class RoleRepository extends BaseRepository
{
    public function __construct(Role $role)
    {
        $this->model=$role;
    }

    public function findById($id)
    {
        return parent::findById($id); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function update(array $input, $id)
    {
        $input["role"]=Str::title($input["role"]);
        return parent::update($input, $id); // TODO: Change the autogenerated stub
    }

    public function create(array $input)
    {
        $input["role"]=Str::title($input["role"]);
        $data= parent::create($input); // TODO: Change the autogenerated stub
        return parent::findById($data->id);
    }
    public function findAll(){
        if($roles=Cache::get('role-list')){
            return $roles;
        }
        $roles=Role::orderBy('role','asc')->paginate();
        Cache::set('role-list',$roles,Carbon::now()->addMinute(60));
        return $roles;
    }

}
