<?php

namespace App\Repositories;

use App\Repositories\BaseRepository;
use App\Models\Rubrique;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\Cache;
class RubriqueRepository extends BaseRepository
{
    public function __construct(Rubrique $rubrique)
    {
        $this->model=$rubrique;
    }

    public function findById($id)
    {
        return parent::findById($id); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function update(array $input, $id)
    {
        $input["rubrique"]=Str::title($input["rubrique"]);
        $input["slugrubrique"]=Str::slug($input["rubrique"]);
        return parent::update($input, $id); // TODO: Change the autogenerated stub
    }

    public function create(array $input)
    {
        $input["rubrique"]=Str::title($input["rubrique"]);
        $input["slugrubrique"]=Str::slug($input["rubrique"]);
        $data= parent::create($input); // TODO: Change the autogenerated stub
        return parent::findById($data->id);
    }
    public function findAll(){
        if($rubriques=Cache::get('rubrique-list')){
            return $rubriques;
        }
        $rubriques=Rubrique::orderBy('rubrique','asc')->paginate();
        Cache::set('rubrique-list',$rubriques,Carbon::now()->addMinute(60));
        return $rubriques;
    }

}
