<?php

namespace App\Repositories;

use App\Repositories\BaseRepository;
use App\Models\Typepub;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\Cache;
class TypePubRepository extends BaseRepository
{
    public function __construct(Typepub $typepub)
    {
        $this->model=$typepub;
    }

    public function findById($id)
    {
        return parent::findById($id); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function update(array $input, $id)
    {
        $input["typepub"]=Str::title($input["typepub"]);
        $input["slugtypepub"]=Str::slug($input["typepub"]);
        return parent::update($input, $id); // TODO: Change the autogenerated stub
    }

    public function create(array $input)
    {
        $input["typepub"]=Str::title($input["typepub"]);
        $input["slugtypepub"]=Str::slug($input["typepub"]);
        $data= parent::create($input); // TODO: Change the autogenerated stub
        return parent::findById($data->id);
    }
    public function findAll(){
        if($typepub=Cache::get('typepub-list')){
            return $typepub;
        }
        $typepub=TypePub::orderBy('typepub','asc')->paginate();
        Cache::set('typepub-list',$typepub,Carbon::now()->addMinute(60));
        return $typepub;
    }

}
