<?php

namespace App\Repositories;

use App\Models\Video;
use App\Repositories\BaseRepository;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\Cache;
class VideoRepository extends BaseRepository
{
    public function __construct(Video $video)
    {
        $this->model=$video;
    }

    public function findById($id)
    {
        return parent::findById($id); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function update(array $input, $id)
    {
        return parent::update($input, $id); // TODO: Change the autogenerated stub
    }

    public function create(array $input)
    {
        $data= parent::create($input); // TODO: Change the autogenerated stub
        return parent::findById($data->id);
    }
    public function findAll(){
        if($video=Cache::get('video-list')){
            return $video;
        }
        $roles=Video::orderBy('added_at','desc')->take(100)->paginate(10);
        Cache::set('video-list',$video,Carbon::now()->addMinute(60));
        return $roles;
    }

}
